### PR TITLE
Joinx1.11.2

### PR DESCRIPTION
**Pull request by ernfrid**
$ apt-cache policy joinx1.11
```
joinx1.11:
  Installed: 1.11.1-1~lucid
  Candidate: 1.11.2-1~lucid
  Version table:
     1.11.2-1~lucid 0
       1001 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main Packages
 *** 1.11.1-1~lucid 0
        100 /var/lib/dpkg/status
```

```
$ sudo apt-get install joinx1.11
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libaccess-bridge-java libruby libtspi1 libaccess-bridge-java-jni libxmlrpc-ruby libredis-perl genome-snapshot-deps-trans-abyss ant-optional-gcj
  bam-readcount0.7.3 ant-gcj
Use 'apt-get autoremove' to remove them.
The following packages will be upgraded:
  joinx1.11
1 upgraded, 0 newly installed, 0 to remove and 889 not upgraded.
Need to get 1,086kB of archives.
After this operation, 4,096B disk space will be freed.
WARNING: The following packages cannot be authenticated!
  joinx1.11
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main joinx1.11 1.11.2-1~lucid [1,086kB]
Fetched 1,086kB in 0s (11.4MB/s)
(Reading database ... 442158 files and directories currently installed.)
Preparing to replace joinx1.11 1.11.1-1~lucid (using .../joinx1.11_1.11.2-1~lucid_amd64.deb) ...
Unpacking replacement joinx1.11 ...
Processing triggers for man-db ...
Setting up joinx1.11 (1.11.2-1~lucid) ...

$ joinx1.11 -v
joinx version 1.11.2-1~lucid (commit b5cc6d8) (Package)
install prefix: /usr
share directory: /usr/share/joinx1.11
```

### CODE REVIEW

**Comment by ernfrid** [comment]
Also, please note/confirm that cle_reporting yaml files are currentyl utilize joinx1.10 so this should not affect them.

**Comment by jasonwalker80** [comment]
`cle_docm_report_snvs.yaml` and `cle_docm_report_indels.yaml` both use 1.11.  All other plan files use 1.10 or 1.9.

**Comment by ernfrid** [comment]
Well drat. We can either re-release as 1.12 or provide a test indicating that this new version works just as well as the old. Do we have such a test already in hand? @susannasiebert?

**Comment by ernfrid** [comment]
After thinking this over. I'm closing and I will re-tag and release this as joinx1.12.

**Comment by susannasiebert** [comment]
The trio process test on jenkins should cover this. If you tag this version as 1.12 wouldn't that conflict with  any future 1.12 version? The change in 1.11.1 was the addition of the `allow-same-file` option to `joinx vcf-merge`. So as long as 1.11.2 supports that option as well, you should be ok with tagging 1.11.2 as 1.11 and the cle docm variant reports should work as expected.

**Comment by ernfrid** [comment]
Right, but the new 1.11 version will overwrite the old and the new will output different results (although we believe them to be equivalent). I would much rather not stomp on the old 1.11 and cause a lot of extra work for the CLE if we don't have a compelling reason to do so. I would remove the 1.11.2 version and release a new 1.12 version that is the same code. It would not conflict with new 1.12 versions.

**Comment by susannasiebert** [comment]
Ah, gotcha. I misunderstood what you meant by 'tagging.' Your plan sounds good.

**Pull request closed without merging**
