### PR TITLE
Add dindel-tgi1.01-wu1

### PR DESCRIPTION
**Pull request by iferguson90**
Package `dindel-tgi1.01-wu1` (1.01-wu1-2) should replace and break `dindel-tgi1.01` (1.01-1). Also add dindel to Precise.

This is a follow-up to #8 and #9.

### CODE REVIEW

**Comment by iferguson90** [comment]
Available versions:
```
$ apt-cache search dindel
dindel-tgi1.01 - Dindel
dindel-tgi1.01-wu1 - Dindel
```
Old version is currently installed:
```
$ echo /usr/bin/dindel* /usr/share/dindel*
/usr/bin/dindel-tgi1.01 /usr/share/dindel-tgi1.01
```
Install the new version, which removes the old version:
```
$ sudo apt-get install dindel-tgi1.01-wu1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libruby libxmlrpc-ruby bam-readcount0.7.3
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  dindel-tgi1.01
The following packages will be upgraded:
  dindel-tgi1.01-wu1
1 upgraded, 0 newly installed, 1 to remove and 179 not upgraded.
Need to get 404kB of archives.
After this operation, 1,016kB disk space will be freed.
Do you want to continue [Y/n]? Y
WARNING: The following packages cannot be authenticated!
  dindel-tgi1.01-wu1
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main dindel-tgi1.01-wu1 1.01-wu1-2 [404kB]
Fetched 404kB in 0s (10.5MB/s)
(Reading database ... 439636 files and directories currently installed.)
Removing dindel-tgi1.01 ...
(Reading database ... 439619 files and directories currently installed.)
Preparing to replace dindel-tgi1.01-wu1 1.01-wu1-1 (using .../dindel-tgi1.01-wu1_1.01-wu1-2_amd64.deb) ...
Unpacking replacement dindel-tgi1.01-wu1 ...
Setting up dindel-tgi1.01-wu1 (1.01-wu1-2) ...
```
New version is installed...
```
$ echo /usr/bin/dindel* /usr/share/dindel*
/usr/bin/dindel-tgi1.01-wu1 /usr/share/dindel-tgi1.01-wu1
```
And it works:
```
$ dindel-tgi1.01-wu1 --kittens | head
Error parsing input options. Usage:

[Required] :
  --ref arg                                     fasta reference sequence
                                                (should be indexed with .fai
                                                file)
  --outputFile arg                              file-prefix for output results

[Required] Program option:
  --analysis arg (=indels) Analysis type:
```

**Comment by davidlmorton** [comment]
+1 although it might be overkill to make a pr for this... opinions?

**Comment by iferguson90** [comment]
(I was under the impression that PRs are required for genome-snapshot-deps.)

**Comment by acoffman** [comment]
+1

And, I think Ian is correct that PRs are required for genome-snapshot-deps.

**Comment by jasonwalker80** [comment]
For clarity, review of genome-snapshot-deps is related to https://jira.gsc.wustl.edu/browse/AR-876

**Pull request merged**
