### PR TITLE
update to joinx1.12

### PR DESCRIPTION
**Pull request by ernfrid**
This fixes a memory error in joinx1.11 vcf-merge but also alters ordering due to changes in the sort algorithm. 

```
$  apt-cache policy joinx1.12
joinx1.12:
  Installed: (none)
  Candidate: 1.12.0-1~lucid
  Version table:
     1.12.0-1~lucid 0
       1001 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main Packages
```
```
$ sudo apt-get install joinx1.12
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libmarble4 python-packagekit libpackagekit-qt-12 libaccess-bridge-java libksane0 ktorrent-data libqca2-plugin-ossl libplasma-geolocation-interface4
  libplasmaclock4 libweather-ion4 libmimelib4 libkexiv2-8 mysql-server-core-5.1 libruby liblqr-1-0 libtspi1 libaccess-bridge-java-jni libkpgp4
  libxmlrpc-ruby libtaskmanager4 krosspython libksieve4 kdepimlibs-data liblensfun-data libplasmagenericshell4 liblensfun0 packagekit
  genome-snapshot-deps-trans-abyss libkscreensaver5 libpackagekit-glib2-12 chromium-browser-inspector bam-readcount0.7.3 marble-data libkfontinst4
  libplasma-applet-system-monitor4 dpatch libmsn0.3 libkdcraw8 packagekit-backend-apt
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  joinx1.12
0 upgraded, 1 newly installed, 0 to remove and 365 not upgraded.
Need to get 1,086kB of archives.
After this operation, 3,096kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  joinx1.12
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main joinx1.12 1.12.0-1~lucid [1,086kB]
Fetched 1,086kB in 0s (11.3MB/s)
Selecting previously deselected package joinx1.12.
(Reading database ... 454298 files and directories currently installed.)
Unpacking joinx1.12 (from .../joinx1.12_1.12.0-1~lucid_amd64.deb) ...
Processing triggers for man-db ...
Setting up joinx1.12 (1.12.0-1~lucid) ...
```
```
$ joinx1.12 -v
joinx version 1.12.0-1~lucid (commit b5cc6d8) (Package)
install prefix: /usr
share directory: /usr/share/joinx1.12
```

### CODE REVIEW

**Comment by ernfrid** [comment]
On an OpenStack precise VM,

```
$ apt-cache policy joinx1.12
joinx1.12:
  Installed: (none)
  Candidate: 1.12.0-1~precise
  Version table:
     1.12.0-1~precise 0
        500 http://repo.gsc.wustl.edu/ubuntu/ precise-genome-development/main amd64 Packages
```

```
$ sudo apt-get install joinx1.12
sudo: unable to resolve host dlarson-precise
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
 joinx1.12
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 1,086 kB of archives.
After this operation, 3,096 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
 joinx1.12
Install these packages without verification [y/N]? y
Get:1 http://repo.gsc.wustl.edu/ubuntu/ precise-genome-development/main joinx1.12 amd64 1.12.0-1~precise [1,086 kB]
Fetched 1,086 kB in 0s (21.9 MB/s)
Selecting previously unselected package joinx1.12.
(Reading database ... 47560 files and directories currently installed.)
Unpacking joinx1.12 (from .../joinx1.12_1.12.0-1~precise_amd64.deb) ...
Processing triggers for man-db ...
Setting up joinx1.12 (1.12.0-1~precise) ...
update-alternatives: using /usr/bin/joinx1.12 to provide /usr/bin/joinx (joinx) in auto mode.
update-alternatives: using /usr/share/man/man1/joinx1.12.1.gz to provide /usr/share/man/man1/joinx.1.gz (joinx.1.gz) in auto mode.
```
```
$ joinx1.12 -v
joinx version 1.12.0-1~precise (commit b5cc6d8) (Package)
install prefix: /usr
share directory: /usr/share/joinx1.12
```

**Comment by susannasiebert** [comment]
+1

**Comment by tmooney** [comment]
+1 package installed for me! :package:

**Comment by ernfrid** [comment]
@tmooney pointed out he got joinx1.11.2 along for the ride as well. I am going to hold on this until @mcallaway and I get that removed from the apt repo.

**Comment by ernfrid** [comment]
@tmooney - we should be repaired now. I have just downgraded my workstation. Can you confirm as well?

**Comment by tmooney** [comment]
Yep, I was able to downgrade. Looks like 1.11.1 is back:
```
$ joinx1.11 --version
joinx version 1.11.1-2~lucid (commit 414da6f) (Package)
install prefix: /usr
share directory: /usr/share/joinx1.11
```

**Comment by ernfrid** [comment]
Wonderful. Merging.

Thanks a million @susannasiebert, @tmooney, @mcallaway.

**Pull request merged**
