### PR TITLE
Update to sra-toolkit 2.4.3

### PR DESCRIPTION
**Pull request by iferguson90**

### CODE REVIEW

**Comment by nnutter** [comment]
Please show proof that `genome-snapshot-deps` can be installed.

**Comment by iferguson90** [comment]
Yeah, this is waiting on my workstation coming back up, but figure I'd make the pull request now. FWIW bdericks was able to install on his workstation.

**Comment by iferguson90** [comment]
:heavy_check_mark: ＊ｐｒｏｏｆ＊
```
$ sudo apt-get update
...
$ sudo apt-get install sra-toolkit
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libruby libxmlrpc-ruby bam-readcount0.7.3
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  sra-toolkit-libs0
The following packages will be upgraded:
  sra-toolkit
1 upgraded, 0 newly installed, 1 to remove and 178 not upgraded.
Need to get 40.2MB of archives.
After this operation, 6,070kB disk space will be freed.
Do you want to continue [Y/n]? Y
WARNING: The following packages cannot be authenticated!
  sra-toolkit
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main sra-toolkit 2.4.3-0ubuntu0tgi2 [40.2MB]
Fetched 40.2MB in 3s (11.7MB/s)
(Reading database ... 439578 files and directories currently installed.)
Removing sra-toolkit-libs0 ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
(Reading database ... 439572 files and directories currently installed.)
Preparing to replace sra-toolkit 2.4.3-0ubuntu0tgi1 (using .../sra-toolkit_2.4.3-0ubuntu0tgi2_amd64.deb) ...
Unpacking replacement sra-toolkit ...
Setting up sra-toolkit (2.4.3-0ubuntu0tgi2) ...
```

And it works:
```
$ sam-dump -V

sam-dump : 2.4.3
```

Finally, `sra-toolkit-libs0` is deconfigured:
```
$ dpkg -s sra-toolkit-libs0
Package: sra-toolkit-libs0
Status: deinstall ok config-files
...
```

**Comment by nnutter** [comment]
Where did you upload the precise package to?

**Comment by iferguson90** [comment]
@nnutter, nowhere, is there a separate build and dput I need to do for precise?

**Comment by nnutter** [comment]
Yep.

**Comment by iferguson90** [comment]
Will rebuilding with `--changes-option='-DDistribution=precise-genome-development'` and `dput precise-genome-development` do it?

**Comment by iferguson90** [comment]
No dice:

```
$ dput precise-genome-development sra-sdk_2.4.3-0ubuntu0tgi2_amd64.changes 
Checking signature on .changes
gpg: Signature made Tue 03 Feb 2015 03:55:05 PM CST using RSA key ID 2D696F93
gpg: Good signature from "Ian Ferguson <iferguso@genome.wustl.edu>"
Good signature on /gscuser/iferguso/packaging/sra-toolkit-precise/sra-sdk_2.4.3-0ubuntu0tgi2_amd64.changes.
Checking signature on .dsc
gpg: Signature made Tue 03 Feb 2015 03:54:55 PM CST using RSA key ID 2D696F93
gpg: Good signature from "Ian Ferguson <iferguso@genome.wustl.edu>"
Good signature on /gscuser/iferguso/packaging/sra-toolkit-precise/sra-sdk_2.4.3-0ubuntu0tgi2.dsc.
Package includes an .orig.tar.gz file although the debian revision suggests
that it might not be required. Multiple uploads of the .orig.tar.gz may be
rejected by the upload queue management software.
Uploading to precise-genome-development (via scp to repo.gsc.wustl.edu):
sra-sdk_2.4.3-0ubuntu0tgi2.dsc                                                                                                                                                                                                                100% 2042     2.0KB/s   00:00
sra-sdk_2.4.3.orig.tar.gz                                                                                                                                                                                                                     100% 1536KB   1.5MB/s   00:00
sra-sdk_2.4.3-0ubuntu0tgi2.debian.tar.gz                                                                                                                                                                                                      100%   25KB  24.6KB/s   00:00
sra-toolkit_2.4.3-0ubuntu0tgi2_amd64.deb                                                                                                                                                                                                      100%   38MB  12.8MB/s   00:03
sra-sdk_2.4.3-0ubuntu0tgi2_amd64.changes                                                                                                                                                                                                      100% 2590     2.5KB/s   00:00
Successfully uploaded packages.
File "pool/main/s/sra-sdk/sra-sdk_2.4.3-0ubuntu0tgi2.dsc" is already registered with different checksums!
md5 expected: 7dd878fd7c08afb7440efa327599b0f6, got: 64161eab5934b313695a6b244c85f442
sha1 expected: 1e59a2321fab9497b8ba75b6bd1e919117cd9d05, got: 5d29e889f3ce9e0e7f99342300da65462086b332
sha256 expected: 22fa48b28a1789658d857e50563da1e6cd07158988c32209228686c8999f2c4e, got: 941bf7e063a86504d6ff251fa29670d99ab40bebbafbf052c330bc9135f5c7f0
There have been errors!
Error: post upload command failed.
```

**Comment by nnutter** [comment]
You should read [INFOSYS-9443](https://jira.gsc.wustl.edu/browse/INFOSYS-9443) to see some things to watch out for.

As far as building the package for Lucid and Precise, since `repo.gsc.wustl.edu` shares a single pool of packages for multiple distributions you have to produce two differently named (really versioned) packages.  You can do this by editing the version by hand but that means there are two (ephemeral) versions of the source package rather than just the binary package.  Some build tools support achieving this using the same source package.  This was previously done using `sbuild` on `vmpool39`.  For example,

```
# build a source package
$ git-buildpackage -us -uc -S --changes-option='-DDistribution=precise-genome-development,lucid-genome-development'
 
# build binaries
$ sbuild --append-to-version=~lucid --chroot=lucid-amd64 --dist=lucid-genome-development --arch-all sra-sdk_2.3.3-4-0ubuntu0tgi2.dsc
$ sbuild --append-to-version=~precise --chroot=precise-amd64 --dist=precise-genome-development --arch-all sra-sdk_2.3.3-4-0ubuntu0tgi2.dsc
```

**Comment by iferguson90** [comment]
I will give separate binary builds a try.

On a separate note I'm worried that replacing 2.3.4 will break existing workflows. The new version does not contain the libs in the old version.

I'm also not sure why this package is not named and versioned like our other packages (ie the package name would be `sra-toolkit2.4.3` and the version would be `2.4.3-N`).

**Comment by mkiwala** [comment]
@brummett is debugging a a test failure that is related to `/usr/bin/sra-dbcc` missing.  Does the new toolkit pacakge provide `sra-dbcc`?

**Comment by mkiwala** [comment]
It looks like `sra-dbcc` was provided in toolkit version 2.3.5, but not in 2.4.4.  I could not find any documentation of why the tool was removed, how .sra files should be checked, or even whether it's necessary to check .sra files anymore.  I've emailed the sra-tools alias at ncbi for guidance.

**Comment by mkiwala** [comment]
I heard back from the sra-tools folks at ncbi.  They say to use vdb-validate instead of sra-dbcc.  I checked, and vdb-validate is installed in our /usr/bin now.

**Comment by nnutter** [comment]
`sra-toolkit` v2.4.4 got deployed everywhere because it's also in the `team_general ` Puppet module:

```
$ git grep -A 1 'package.*sra-toolkit'
site/team_general/manifests/init.pp:    package{'sra-toolkit':
site/team_general/manifests/init.pp-        ensure  => latest,
```

**Comment by iferguson90** [comment]
Is `vdb-validate` a a drop in replacement for `sra-dbcc`?

**Comment by mkiwala** [comment]
Help for `sra-dbcc` [here](https://github.com/ncbi/sratoolkit/blob/master/tools/sra-dbcc/sra-dbcc.c#l1244-1266).  Help for `vdb-validate`:

```
mkiwala@linus82:~ $ vdb-validate -h
Usage: vdb-validate [options] path [ path... ]

  Examine directories, files and VDB objects,
  reporting any problems that can be detected.

Components md5s are always checked if present.

Options:
  -B|--BLOB-CRC <yes | no>         Check blobs CRC32 (default: yes)
  -I|--REFERENTIAL-INTEGRITY <yes | no>  Check data referential integrity for
                                   databases (default: yes)
  -C|--CONSISTENCY-CHECK <yes | no>  Deeply check data consistency for tables
                                   (default: no)
  -x|--exhaustive                  Continue checking object for all possible
                                   errors (default: false)
  -h|--help                        Output brief explanation for the program.
  -V|--version                     Display the version of the program then
                                   quit.
  -L|--log-level <level>           Logging level as number or enum string. One
                                   of (fatal|sys|int|err|warn|info) or (0-5)
                                   Current/default is warn
  -v|--verbose                     Increase the verbosity of the program
                                   status messages. Use multiple times for more
                                   verbosity. Negates quiet.
  -q|--quiet                       Turn off all status messages for the
                                   program. Negated by verbose.
  --option-file <file>             Read more options and parameters from the
                                   file.
```

**Comment by mkiwala** [comment]
> Is vdb-validate a a drop in replacement for sra-dbcc?

Looks like `vdb-validate` is not strictly a drop-in replacement for `sra-dbcc`.  It is probably good enough to replace any usage of `sra-dbcc` with a simple invocation of `vdb-validate`, specifying only the file to be validated and using no flags.

**Comment by brummett** [comment]
sra-dbcc is used in two places:
    InstrumentData/Command/Import/WorkFlow/SraToBam.pm
    InstrumentData/Command/Export/Samplesheet.pm
The first instance was causing the tests to hang on Jenkins.  I'm not sure what triggers the second one.

**Comment by iferguson90** [comment]
The call in `InstrumentData/Command/Import/WorkFlow/SraToBam.pm` is fixed in genome/genome#424. So, that should at least fix tests, but `InstrumentData/Command/Export/Samplesheet.pm` should still be updated.

**Comment by iferguson90** [comment]
I think it's safe to merge this since Puppet has already deployed this package without us. I simply removed the changes to Precise deps. Anways, I'll leave this open for 24 more hours if anyone would like to comment further. :boar:

**Comment by ebelter** [comment]
I say DO IT :smile:

**Comment by nnutter** [comment]
:+1:

```
$ apt-cache policy sra-toolkit | grep -m 2 2.4.3-0ubuntu0tgi2
  Installed: 2.4.3-0ubuntu0tgi2
  Candidate: 2.4.3-0ubuntu0tgi2
```

**Pull request merged**
