### PR TITLE
Lucid perl deps: add libnet-ldap-perl

### PR DESCRIPTION
**Pull request by ebelter**

### CODE REVIEW

**Comment by tmooney** [comment]
Are we using `libconvert-asn1-perl` for anything?  The package manager should figure out to install that dependency for us.

**Comment by ebelter** [comment]
@tmooney Nope, added it as a dep of net-ldap. I will remove it.

**Comment by tmooney** [comment]
+1 :page_with_curl:

**Comment by brummett** [comment]
+1

**Pull request merged**
