### PR TITLE
Bcftools

### PR DESCRIPTION
**Pull request by iferguson90**
Recent versions of bcftools. Proof that these packages work is Coming Soon™.

### CODE REVIEW

**Comment by iferguson90** [comment]
Proof that the packages can be installed:
```
[linus47] (iferguso) $ sudo apt-get install bcftools1.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libruby libxmlrpc-ruby bam-readcount0.7.3
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  bcftools1.0
0 upgraded, 1 newly installed, 0 to remove and 192 not upgraded.
Need to get 443kB of archives.
After this operation, 1,008kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  bcftools1.0
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main bcftools1.0 1.0-1 [443kB]
Fetched 443kB in 0s (10.2MB/s)
Selecting previously deselected package bcftools1.0.
(Reading database ... 442743 files and directories currently installed.)
Unpacking bcftools1.0 (from .../bcftools1.0_1.0-1_amd64.deb) ...
Processing triggers for man-db ...
Setting up bcftools1.0 (1.0-1) ...
```
```
[linus47] (iferguso) $ sudo apt-get install bcftools1.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libruby libxmlrpc-ruby bam-readcount0.7.3
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  bcftools1.1
0 upgraded, 1 newly installed, 0 to remove and 192 not upgraded.
Need to get 478kB of archives.
After this operation, 1,085kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  bcftools1.1
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main bcftools1.1 1.1-1 [478kB]
Fetched 478kB in 0s (10.6MB/s)
Selecting previously deselected package bcftools1.1.
(Reading database ... 442752 files and directories currently installed.)
Unpacking bcftools1.1 (from .../bcftools1.1_1.1-1_amd64.deb) ...
Processing triggers for man-db ...
Setting up bcftools1.1 (1.1-1) ...
```
```
[linus47] (iferguso) $ sudo apt-get install bcftools1.2
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libruby libxmlrpc-ruby bam-readcount0.7.3
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  bcftools1.2
0 upgraded, 1 newly installed, 0 to remove and 192 not upgraded.
Need to get 542kB of archives.
After this operation, 1,221kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  bcftools1.2
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main bcftools1.2 1.2-1 [542kB]
Fetched 542kB in 0s (10.7MB/s)
Selecting previously deselected package bcftools1.2.
(Reading database ... 442761 files and directories currently installed.)
Unpacking bcftools1.2 (from .../bcftools1.2_1.2-1_amd64.deb) ...
Processing triggers for man-db ...
Setting up bcftools1.2 (1.2-1) ...
```

**Comment by iferguson90** [comment]
Proof that bcftools works!
```
[linus47] (iferguso) $ bcftools1.0 --version
bcftools 1.0
Using htslib 1.0
Copyright (C) 2014 Genome Research Ltd.
```
```
[linus47] (iferguso) $ bcftools1.1 --version
bcftools 1.1
Using htslib 1.1
Copyright (C) 2014 Genome Research Ltd.
```
```
[linus47] (iferguso) $ bcftools1.2 --version
bcftools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by iferguson90** [comment]
I should add that `bcftools1.2` has a dependency on `libgsl0ldbl`. The dependency *is* specified in `debian/control`, and it's already installed site-wide (probably for some other package). I'm just curious if there's anything else I need to add to `genome-snapshot-deps` to account for this.

**Comment by tmooney** [comment]
+1 :phone: These install as well!

I don't think you need anything extra in `genome-snapshot-deps`.  Occasionally locally versions have to be "pinned", but that happens outside the packages themselves.

**Comment by iferguson90** [comment]
Updated to fix binary installation locations, similar to #17.

:ballot_box_with_check: Installs

```
[linus47] (iferguso) $ apt-cache policy bcftools1.0 bcftools1.1 bcftools1.2
bcftools1.0:
  Installed: 1.0-2
  Candidate: 1.0-2
  Version table:
 *** 1.0-2 0
       1001 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main Packages
        100 /var/lib/dpkg/status
bcftools1.1:
  Installed: 1.1-2
  Candidate: 1.1-2
  Version table:
 *** 1.1-2 0
       1001 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main Packages
        100 /var/lib/dpkg/status
bcftools1.2:
  Installed: 1.2-2
  Candidate: 1.2-2
  Version table:
 *** 1.2-2 0
       1001 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main Packages
        100 /var/lib/dpkg/status
```

:ballot_box_with_check: Works

```
[linus47] (iferguso) $ for v in 1.0 1.1 1.2 ; do bcftools$v --version ; echo ; done
bcftools 1.0
Using htslib 1.0
Copyright (C) 2014 Genome Research Ltd.

bcftools 1.1
Using htslib 1.1
Copyright (C) 2014 Genome Research Ltd.

bcftools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

:ballot_box_with_check: Fixes install paths.

```
[linus47] (iferguso) $ for d in lib share ; do for v in 1.0 1.1 1.2 ; do find /usr/$d/bcftools$v -executable -type f ; done ; done
/usr/lib/bcftools1.0/plot-vcfstats
/usr/lib/bcftools1.1/plot-vcfstats
/usr/lib/bcftools1.2/plot-vcfstats
/usr/share/bcftools1.0/vcfutils.pl
/usr/share/bcftools1.1/vcfutils.pl
/usr/share/bcftools1.2/vcfutils.pl
```

**Pull request merged**
