### PR TITLE
introduce debian package for vcflib

### PR DESCRIPTION
**Pull request by indraniel**
This is a pull request to add [vcflib][1] as a dependency to GMS.  A customized debian package, `vcflib-tgi1.0`, was created based upon the code changes made in the [debian branch of genome-vendor/vcflib][2].

Nothing in [genome][3] depends on this package yet, but it will in the future.  Please see our internal JIRA issue [BIO-1387][4] for more information.

The package has been placed into our internal APT repo.  You can test its installation by executing the following command on our workstations:

    apt-get install vcflib-tgi1.0

Here's some additional package details:

```
$ apt-cache show vcflib-tgi1.0
Package: vcflib-tgi1.0
Version: 2015.03.13-1
Architecture: amd64
Maintainer: Genome Developers <genome-dev@genome.wustl.edu>
Installed-Size: 42944
Depends: libc6 (>= 2.7), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.4.0), zlib1g (>= 1:1.2.0.2), python2.7, perl, libsqlite3-0, r-base, r-cran-ggplot2, r-cran-plyr
Homepage: https://github.com/ekg/vcflib
Priority: optional
Section: science
Filename: pool/main/v/vcflib-tgi1.0/vcflib-tgi1.0_2015.03.13-1_amd64.deb
Size: 19052480
SHA256: 9e376b0fa119d029ee1e42a7c2f663e62a30395f19ef0f52973eecb043374b00
SHA1: 1dac857110b9d271cd8455a59736a160f72f4855
MD5sum: 16d50df68cc9db6cb32d68624b712353
Description: tools for parsing and manipulating VCF files
 vcflib is a suite of programs (C++, bash, perl, R & python) for parsing
 and manipulating Variant Call Format (VCF) files used in genomic studies.
 .
 This package is a custom Genome Institute at Washington University in
 St. Louis (TGI) edition of https://github.com/ekg/vcflib.  It is based on
 git commit "b1e9b31d2d95f957f86cdfd1e7c9ec25b4950ee8" of that repository.
```

The files that the package installs are listed in the [debian install file][5].

Let me know if there's any additional information I need to provide, or if I've missed any protocol in the APIPE debian package creation and deployment process.

[1]: https://github.com/ekg/vcflib
[2]: https://github.com/genome-vendor/vcflib/tree/debian
[3]: https://github.com/genome/genome
[4]: https://jira.gsc.wustl.edu/browse/BIO-1387
[5]: https://github.com/genome-vendor/vcflib/blob/debian/debian/install

### CODE REVIEW

**Comment by nnutter** [comment]
:+1: 

```
$ sudo apt-get install vcflib-tgi1.0=2015.03.13-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  vcflib-tgi1.0
0 upgraded, 1 newly installed, 0 to remove and 249 not upgraded.
Need to get 19.1MB of archives.
After this operation, 44.0MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  vcflib-tgi1.0
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main vcflib-tgi1.0 2015.03.13-1 [19.1MB]
Fetched 19.1MB in 1s (11.7MB/s)         
Selecting previously deselected package vcflib-tgi1.0.
(Reading database ... 489258 files and directories currently installed.)
Unpacking vcflib-tgi1.0 (from .../vcflib-tgi1.0_2015.03.13-1_amd64.deb) ...
Setting up vcflib-tgi1.0 (2015.03.13-1) ...
```

**Comment by indraniel** [comment]
Thanks @nnutter .  Looks like I still need another +1.

**Comment by ebelter** [comment]
The package installs for my ok through apt-get. I also tried to install genome-snapshot deps by cloning your repo, and doing the procedures in the README to make and install genome-snapshot-deps. It fails with this message:

dpkg: dependency problems prevent configuration of genome-snapshot-deps:
 genome-snapshot-deps depends on genome-snapshot-deps-apps-tgi (= 2014.11.12-1); however:
  Package genome-snapshot-deps-apps-tgi is not configured yet.

Maybe this isn't a real problem. @nnutter do you have an idea of why this would not work?

**Comment by mkiwala** [comment]
> Maybe this isn't a real problem.

I agree with that statement.  I think I've seen the same message when following the instructions in the README while adding a different dependency to genome-snapshot-deps.  If the message indicates a problem, the a problem it is not with this PR.

**Comment by ebelter** [comment]
+1

**Comment by indraniel** [comment]
@ebelter: I don't see your error when I try to rebuild the debian package from scratch again. Very strange.

**Comment by indraniel** [comment]
@nnutter is investigating into the installation issue @ebelter saw.  I'll await for his response before attempting to merge this pull request.

**Comment by nnutter** [comment]
I also had no issue so go ahead and merge.

**Pull request merged**
