### PR TITLE
Samtools

### PR DESCRIPTION
**Pull request by iferguson90**
Recent versions of samtools. Proof that these packages work is Coming Soon™.

### CODE REVIEW

**Comment by iferguson90** [comment]
Proof that the packages can be installed:
```
[linus47] (iferguso) $ sudo apt-get install samtools1.0
[sudo] password for iferguso:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libruby libxmlrpc-ruby bam-readcount0.7.3
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  samtools1.0
0 upgraded, 1 newly installed, 0 to remove and 192 not upgraded.
Need to get 425kB of archives.
After this operation, 1,016kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  samtools1.0
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main samtools1.0 1.0-1 [425kB]
Fetched 425kB in 0s (9,138kB/s)
Selecting previously deselected package samtools1.0.
(Reading database ... 442671 files and directories currently installed.)
Unpacking samtools1.0 (from .../samtools1.0_1.0-1_amd64.deb) ...
Processing triggers for man-db ...
Setting up samtools1.0 (1.0-1) ...
```
```
[linus47] (iferguso) $ sudo apt-get install samtools1.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libruby libxmlrpc-ruby bam-readcount0.7.3
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  samtools1.1
0 upgraded, 1 newly installed, 0 to remove and 192 not upgraded.
Need to get 427kB of archives.
After this operation, 1,020kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  samtools1.1
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main samtools1.1 1.1-1 [427kB]
Fetched 427kB in 0s (10.1MB/s)
Selecting previously deselected package samtools1.1.
(Reading database ... 442695 files and directories currently installed.)
Unpacking samtools1.1 (from .../samtools1.1_1.1-1_amd64.deb) ...
Processing triggers for man-db ...
Setting up samtools1.1 (1.1-1) ...
```
```
[linus47] (iferguso) $ sudo apt-get install samtools1.2
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libruby libxmlrpc-ruby bam-readcount0.7.3
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  samtools1.2
0 upgraded, 1 newly installed, 0 to remove and 192 not upgraded.
Need to get 446kB of archives.
After this operation, 1,044kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  samtools1.2
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main samtools1.2 1.2-1 [446kB]
Fetched 446kB in 0s (10.4MB/s)
Selecting previously deselected package samtools1.2.
(Reading database ... 442719 files and directories currently installed.)
Unpacking samtools1.2 (from .../samtools1.2_1.2-1_amd64.deb) ...
Processing triggers for man-db ...
Setting up samtools1.2 (1.2-1) ...
```

**Comment by iferguson90** [comment]
Proof that samtools works!
```
[linus47] (iferguso) $ samtools1.0 --version
samtools 1.0
Using htslib 1.0
Copyright (C) 2014 Genome Research Ltd.
```
```
[linus47] (iferguso) $ samtools1.1 --version
samtools 1.1
Using htslib 1.1
Copyright (C) 2014 Genome Research Ltd.
```
```
[linus47] (iferguso) $ samtools1.2 --version
samtools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.
```

**Comment by indraniel** [comment]
+1

only one file has been changed.  it seems correct to me

**Comment by tmooney** [comment]
+1 packages installed for me :telephone_receiver:

**Comment by iferguson90** [comment]
Here's goes nothing! :honeybee:

**Pull request merged**
