### PR TITLE
Updated samtools packages

### PR DESCRIPTION
**Pull request by iferguson90**
A :cool: and :new: version of **samtools**, :ok:?

I incorrectly patched the Makefile in the previous versions of these packages, and the “miscellaneous” binaries were not being installed. These versions fix that.

:ballot_box_with_check: Installs?

```
[linus47] (iferguso) $ apt-cache policy samtools1.0 samtools1.1 samtools1.2
samtools1.0:
  Installed: 1.0-2
  Candidate: 1.0-2
  Version table:
 *** 1.0-2 0
       1001 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main Packages
        100 /var/lib/dpkg/status
samtools1.1:
  Installed: 1.1-2
  Candidate: 1.1-2
  Version table:
 *** 1.1-2 0
       1001 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main Packages
        100 /var/lib/dpkg/status
samtools1.2:
  Installed: 1.2-2
  Candidate: 1.2-2
  Version table:
 *** 1.2-2 0
       1001 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main Packages
        100 /var/lib/dpkg/status
```

:ballot_box_with_check: Works?

```
[linus47] (iferguso) $ for x in samtools1.0 samtools1.1 samtools1.2 ; do $x --version ; echo ; done
samtools 1.0
Using htslib 1.0
Copyright (C) 2014 Genome Research Ltd.

samtools 1.1
Using htslib 1.1
Copyright (C) 2014 Genome Research Ltd.

samtools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.
```

:ballot_box_with_check: Fixes problem with previous packages? (Missing miscellaneous binaries under `/usr/lib/`)

```
[linus47] (iferguso) $ find /usr/lib/samtools1.* -executable
/usr/lib/samtools1.0
/usr/lib/samtools1.0/maq2sam-long
/usr/lib/samtools1.0/maq2sam-short
/usr/lib/samtools1.0/md5fa
/usr/lib/samtools1.0/md5sum-lite
/usr/lib/samtools1.0/wgsim
/usr/lib/samtools1.0/ace2sam
/usr/lib/samtools1.1
/usr/lib/samtools1.1/maq2sam-long
/usr/lib/samtools1.1/maq2sam-short
/usr/lib/samtools1.1/md5fa
/usr/lib/samtools1.1/md5sum-lite
/usr/lib/samtools1.1/wgsim
/usr/lib/samtools1.1/ace2sam
/usr/lib/samtools1.2
/usr/lib/samtools1.2/maq2sam-long
/usr/lib/samtools1.2/maq2sam-short
/usr/lib/samtools1.2/md5fa
/usr/lib/samtools1.2/md5sum-lite
/usr/lib/samtools1.2/wgsim
/usr/lib/samtools1.2/ace2sam
```

### CODE REVIEW

**Comment by iferguson90** [comment]
For the record, I thought it was a bit strange to put these miscellaneous binaries under `/usr/lib/`, but that’s what the official Debian and Ubuntu samtools packages do, so that’s what I’ll do. I checked Homebrew, and they link them all into `$PREFIX/bin`.

**Comment by ernfrid** [comment]
@iferguson90  - will this replace the default install of samtools or will it only add the `/usr/lib/samtools1.2-2 ?

**Comment by iferguson90** [comment]
@ernfrid 
These packages supersede the versions of samtools I uploaded yesterday, versions `1.0-1`, `1.1-1`, and `1.2-1`. Those `-1` versions provided:
```
/usr/bin/samtools1.x
/usr/share/samtools1.x/*
```

These new `-2` versions provide:
```
/usr/bin/samtools1.x
/usr/lib/samtools1.x/*
/usr/share/samtools1.x/*
```

In any case, none of these packages intersect with the default install of samtools or anything in `/gsc/pkg/bio` or `/gsc/bin`.

For example:
```
[linus47] (iferguso) $ samtools 2>&1 | head -3

Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.18 (r982:295)

[linus47] (iferguso) $ which samtools
/gsc/bin/samtools
```

**Comment by ernfrid** [comment]
Wonderful. I was a little concerned about naked samtools calls in our code based, but this sounds like it should not be an issue.

**Comment by tmooney** [comment]
+1 :fast_forward: Looks like it works! I was able to upgrade the packages and I see your new executables.

```
$ ls /usr/lib/samtools1.*/
/usr/lib/samtools1.0/:
./  ../  ace2sam*  maq2sam-long*  maq2sam-short*  md5fa*  md5sum-lite*  wgsim*

/usr/lib/samtools1.1/:
./  ../  ace2sam*  maq2sam-long*  maq2sam-short*  md5fa*  md5sum-lite*  wgsim*

/usr/lib/samtools1.2/:
./  ../  ace2sam*  maq2sam-long*  maq2sam-short*  md5fa*  md5sum-lite*  wgsim*
```

**Pull request merged**
