### PR TITLE
Version 0.1.10-1 of libptero-perl

### PR DESCRIPTION
**Pull request by mkiwala**
The new version of libptero-perl is in the TGI repo and it installs (proof below).

@davidlmorton created genome/genome#976 which depended on having the new libptero-perl installed, and his tests passed.

```
mkiwala@linus82:~ $ apt-cache policy libptero-perl
libptero-perl:
  Installed: 0.1.9-1
  Candidate: 0.1.10-1
  Version table:
     0.1.10-1 0
       1001 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main Packages
 *** 0.1.9-1 0
        100 /var/lib/dpkg/status
mkiwala@linus82:~ $ sudo apt-get install libptero-perl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libiw-dev libnspr4-dev libruby libnss3-dev libxmlrpc-ruby libnotify-dev mcollective-nrpe-common xulrunner-1.9.2-dev bam-readcount0.7.3
Use 'apt-get autoremove' to remove them.
The following packages will be upgraded:
  libptero-perl
1 upgraded, 0 newly installed, 0 to remove and 826 not upgraded.
Need to get 33.9kB of archives.
After this operation, 0B of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libptero-perl
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main libptero-perl 0.1.10-1 [33.9kB]
Fetched 33.9kB in 0s (0B/s)
(Reading database ... 440077 files and directories currently installed.)
Preparing to replace libptero-perl 0.1.9-1 (using .../libptero-perl_0.1.10-1_all.deb) ...
Unpacking replacement libptero-perl ...
Processing triggers for man-db ...
Setting up libptero-perl (0.1.10-1) ...
```

### CODE REVIEW

**Comment by tmooney** [comment]
Seems to install!

```
$ apt-cache policy libptero-perl
libptero-perl:
  Installed: 0.1.10-1
  Candidate: 0.1.10-1
  Version table:
 *** 0.1.10-1 0
       1001 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main Packages
        100 /var/lib/dpkg/status
$ grep '$VERSION' /usr/share/perl5/Ptero.pm
our $VERSION = "0.1.10";
```

Is there a convenient way to see if it's working?  In #46 we ran `ptero-view`, but those commands are not working for me either before or after the update.

**Comment by mkiwala** [comment]
@tmooney -- unfortunately `ptero-view` cannot easily work right now because the pre-production deployment of PTero is down until the OpenStack outage on Tuesday morning is complete.  Tuesday, sometime after the outage, @davidlmorton and I will recreate the ptero deployment and `ptero-view` will work.  I'll comment on this PR again once `ptero-view` would work again.

**Comment by davidlmorton** [comment]
To clarify, the ptero-view does not itself depend on our production deployment of PTero, it was simply the  most convenient way to smoke test that it worked.  You could spin up a set of PTero services yourself and point ptero-view at those, or wait for production deployment to be back up.  We have pretty extensive testing of the view code that has to pass before we create the package, but a smoke test is nonetheless comforting.

**Comment by tmooney** [comment]
+1 :shipit:

**Pull request merged**
