### PR TITLE
joinx1.11

### PR DESCRIPTION
**Pull request by tabbott**
Add new joinx version (1.11) for lucid and precise.

### CODE REVIEW

**Comment by tabbott** [comment]
After make all in snapshot deps:

[tabbott@linus129 ~/sw/git/genome] sudo apt-get install joinx1.11
The following NEW packages will be installed:
  joinx1.11
0 upgraded, 1 newly installed, 0 to remove and 675 not upgraded.
2 not fully installed or removed.
Need to get 0B/1,086kB of archives.
After this operation, 3,095kB of additional disk space will be used.
...

[tabbott@linus129 ~/sw/git/genome] sudo dpkg -i *.deb                                                                                                                                                                                        
(Reading database ... 563201 files and directories currently installed.)
Preparing to replace genome-snapshot-deps-apps-external 2015.02.12-1 (using genome-snapshot-deps-apps-external_2015.02.12-1_all.deb) ...
Unpacking replacement genome-snapshot-deps-apps-external ...
Preparing to replace genome-snapshot-deps-apps-tgi 2015.02.12-1 (using genome-snapshot-deps-apps-tgi_2015.02.12-1_all.deb) ...
Unpacking replacement genome-snapshot-deps-apps-tgi ...
Preparing to replace genome-snapshot-deps-flow 2015.02.12-1 (using genome-snapshot-deps-flow_2015.02.12-1_all.deb) ...
Unpacking replacement genome-snapshot-deps-flow ...
Preparing to replace genome-snapshot-deps-lims 2015.02.12-1 (using genome-snapshot-deps-lims_2015.02.12-1_all.deb) ...
Unpacking replacement genome-snapshot-deps-lims ...
Preparing to replace genome-snapshot-deps-perl 2015.02.12-1 (using genome-snapshot-deps-perl_2015.02.12-1_all.deb) ...
Unpacking replacement genome-snapshot-deps-perl ...
Preparing to replace genome-snapshot-deps-python 2015.02.12-1 (using genome-snapshot-deps-python_2015.02.12-1_all.deb) ...
Unpacking replacement genome-snapshot-deps-python ...
Preparing to replace genome-snapshot-deps-r 2015.02.12-1 (using genome-snapshot-deps-r_2015.02.12-1_all.deb) ...
Unpacking replacement genome-snapshot-deps-r ...
Preparing to replace genome-snapshot-deps-refcov 2015.02.12-1 (using genome-snapshot-deps-refcov_2015.02.12-1_all.deb) ...
Unpacking replacement genome-snapshot-deps-refcov ...
Preparing to replace genome-snapshot-deps-ur 2015.02.12-1 (using genome-snapshot-deps-ur_2015.02.12-1_all.deb) ...
Unpacking replacement genome-snapshot-deps-ur ...
Preparing to replace genome-snapshot-deps-workflow 2015.02.12-1 (using genome-snapshot-deps-workflow_2015.02.12-1_all.deb) ...
Unpacking replacement genome-snapshot-deps-workflow ...
Preparing to replace genome-snapshot-deps 2015.02.12-1 (using genome-snapshot-deps_2015.02.12-1_all.deb) ...
Unpacking replacement genome-snapshot-deps ...
Setting up genome-snapshot-deps-apps-external (2015.02.12-1) ...
Setting up genome-snapshot-deps-apps-tgi (2015.02.12-1) ...
Setting up genome-snapshot-deps-flow (2015.02.12-1) ...
Setting up genome-snapshot-deps-lims (2015.02.12-1) ...
Setting up genome-snapshot-deps-perl (2015.02.12-1) ...
Setting up genome-snapshot-deps-python (2015.02.12-1) ...
Setting up genome-snapshot-deps-r (2015.02.12-1) ...
Setting up genome-snapshot-deps-refcov (2015.02.12-1) ...
Setting up genome-snapshot-deps-ur (2015.02.12-1) ...
Setting up genome-snapshot-deps-workflow (2015.02.12-1) ...
Setting up genome-snapshot-deps (2015.02.12-1) ...
[tabbott@linus129 ~/sw/git/genome] echo woot
woot

**Comment by tmooney** [comment]
The package installed for me:
```
$ /usr/bin/joinx1.11 --version
joinx version 1.11.0-1~lucid (commit cf1c34d) (package)
install prefix: /usr
share directory: /usr/share/joinx1.11
$ echo +1
+1
```
+1 :yen:

**Comment by nnutter** [comment]
Also confirmed it's in the Precise repo.  (We don't have to push Precise packages anymore.)

:+1:

**Comment by tabbott** [comment]
Sweet!

**Pull request merged**
