### PR TITLE
update sniper to patch release

### PR DESCRIPTION
**Pull request by ernfrid**
This is a patch release for somatic-sniper. It fixes a bug involved in syncing the tumor/normal BAM files where it would get into an infinite loop if one of the files ended while the two were not at the same position in the genome.

Please do not merge this as I need to run the patch by a few higher ups.

```
$ apt-cache policy somatic-sniper1.0.4
somatic-sniper1.0.4:
  Installed: 1.0.4.2
  Candidate: 1.0.4.2
  Version table:
 *** 1.0.4.2 0
       1001 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main Packages
        100 /var/lib/dpkg/status
```

And then the upgrade

```
$ sudo apt-get install somatic-sniper1.0.4
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libaccess-bridge-java libruby libtspi1 libaccess-bridge-java-jni libxmlrpc-ruby libredis-perl genome-snapshot-deps-trans-abyss
  ant-optional-gcj bam-readcount0.7.3 ant-gcj
Use 'apt-get autoremove' to remove them.
The following packages will be upgraded:
  somatic-sniper1.0.4
1 upgraded, 0 newly installed, 0 to remove and 890 not upgraded.
Need to get 124kB of archives.
After this operation, 310MB disk space will be freed.
WARNING: The following packages cannot be authenticated!
  somatic-sniper1.0.4
Authentication warning overridden.
Get:1 http://repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main somatic-sniper1.0.4 1.0.4.2 [124kB]
Fetched 124kB in 0s (8,643kB/s)
(Reading database ... 442081 files and directories currently installed.)
Preparing to replace somatic-sniper1.0.4 1.0.4 (using .../somatic-sniper1.0.4_1.0.4.2_amd64.deb) ...
Unpacking replacement somatic-sniper1.0.4 ...
Setting up somatic-sniper1.0.4 (1.0.4.2) ...
```

Confirming version - 

```
$ bam-somaticsniper1.0.4 -v
Somatic Sniper version (1.0.4.2) (commit c9d4c02) (Package)
```

### CODE REVIEW

**Comment by nnutter** [comment]
I don't see that you also pushed a `precise` package but you did change the `genome-snapshot-deps` `precise` manifest.

**Comment by ernfrid** [comment]
Doh. Manager-brain. You are right. It should be there now.

**Comment by nnutter** [comment]
:+1:

**Comment by jasonwalker80** [comment]
+1

**Pull request merged**
